app:
    renderLimit: 30 #How many cities should be processed in the same time
    styleDir: style/
    stylesheet: rando.xml
    marker: marker_star.svg
    key: #for dynamic replacing
        cityName: CITY_NAMEASCII
        marker: MARKER_URL
    tmpDir: /tmp/rando-map-data/
    tmpTilesDir: /tmp/rando-map-data/tiles/
    stylesheetTmpDir: /tmp/rando-map-data/
    shpPopulatedPlaceFile: 10m_cultural/ne_10m_populated_places_simple.shp
    placesFile: /tmp/rando-map-data/places.json
    shpFilesDir: /tmp/rando-map-data/
    shpFiles: #Next files should exists before script run:
        - ne_10m_rivers_europe.shp
        - ne_10m_lakes.shp
        - ne_10m_rivers_north_america.shp
        - ne_10m_lakes_europe.shp
        - ne_10m_lakes_north_america.shp
        - 10m_cultural/ne_10m_admin_0_countries.shp
        - 10m_cultural/ne_10m_roads.shp
        - 10m_cultural/ne_10m_admin_1_states_provinces_lines_shp.shp
    citiesFile: /tmp/rando-map-data/cities.json #Important target
    citiesSourceFile: cities.json
    binDir:
        root: bin/
        small: bin/small/
        medium: bin/medium/
        large: bin/large/
    imageSize:
        small: 480
        medium: 800
        large: 1200
    imageQuality: 85
    bboxSize: 3.3 #in degrees
    
